---
title: "mengranma.github.io"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(ggridges)
library(hexbin)
library(plotly)
library(patchwork)
```

```{r data_manipulating}
set.seed(1)


data(ny_noaa)
noaa_data = janitor::clean_names(ny_noaa)
#Create separate variables for year, month, and day.
New_noaa_data = mutate(noaa_data, noaa_data$date, year = as.integer(format(noaa_data$date, format = "%Y")), month = as.integer(format(noaa_data$date, format = "%m")), day = as.integer(format(noaa_data$date, format = "%d")))

#Ensure observations for temperature, precipitation, and snowfall are given in reasonable units.
New_noaa_data = mutate(New_noaa_data,
  tmax = as.numeric(tmax) / 10, 
  tmin = as.numeric(tmin) / 10,
  prcp = as.numeric(prcp) / 10
)
```


Column {data-width=600}
-----------------------------------------------------------------------

### Chart A

```{r plotly_graph_1}
Jan_July_average = New_noaa_data %>%
  select(id, prcp, snow, snwd, tmax, tmin, year, month, day) %>% 
  filter(month == 1 | month == 7) %>% 
  filter(!is.na(tmax) | !is.na(tmin))

plot1 = Jan_July_average %>% 
  sample_n(10000) %>% 
  group_by(id, year, month) %>%
  summarize(mean_tempmax = mean(as.numeric(tmax), na.rm = TRUE)) %>%
  ggplot(aes(x = year, y = mean_tempmax, color = id, alpha = 0.5)) + 
    geom_point() + 
    geom_line() +
    labs(
      title = "Average temperature in each station across years",
      x = "Weather station ID",
      y = "Mean Maxiumum temperature (°C)"
      ) +
  theme(axis.text.x = element_text(angle = 45, size = 6)) +
  theme(legend.position = "bottom") +
  facet_grid(~month)

ggplotly(plot1)
```

Column {data-width=400}
-----------------------------------------------------------------------

### Chart B

```{r plotly_graph_2}
# (i) tmax vs tmin for the full dataset
plot2 = New_noaa_data %>% 
  sample_n(10000) %>%
  ggplot(aes(x = tmax, y = tmin)) + 
    geom_hex() +
    labs(
        title = "Temperature plot",
        x = "Maximum temperature (°C)",
        y = "Minimum temperature (°C)"
      ) +
  theme(axis.text.x = element_text(angle = 45, size = 6))

ggplotly(plot2)
```

### Chart C

```{r plotly_graph_3}
plot3 = New_noaa_data %>% 
  mutate(year = as.factor(year)) %>% 
  filter(snow > 0 & snow < 100) %>%
  sample_n(5000) %>%
  mutate(year = fct_reorder(year, snow)) %>%
  ggplot(aes(x = year, y = snow, color = year)) + 
    geom_boxplot(alpha = .5) +
    labs(
      title = "Distribution of snowfall among different years",
      x = "Snowfall values",
      y = "Distribution of snowfall within each year"
    ) +
      theme(axis.text.x = element_text(angle = 45, size = 6))
ggplotly(plot3)
```

